---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/admin/custom_fields":
    get:
      summary: list custom_fields
      responses:
        '200':
          description: successful
    post:
      summary: create custom_field
      responses:
        '200':
          description: successful
  "/api/admin/custom_fields/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show custom_field
      responses:
        '200':
          description: successful
    patch:
      summary: update custom_field
      responses:
        '200':
          description: successful
    put:
      summary: update custom_field
      responses:
        '200':
          description: successful
    delete:
      summary: delete custom_field
      responses:
        '200':
          description: successful
  "/api/categories":
    get:
      summary: list categories
      tags:
      - Categories
      parameters:
      - name: page
        in: query
        description: Page for pagination
        schema:
          type: integer
      - name: items
        in: query
        description: Number of items per page
        schema:
          type: integer
      responses:
        '200':
          description: successful
  "/api/categories/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show category
      tags:
      - Categories
      responses:
        '200':
          description: successful
  "/api/categories/{category_id}/listings":
    parameters:
    - name: category_id
      in: path
      description: category_id
      required: true
      schema:
        type: string
    get:
      summary: list listings
      responses:
        '200':
          description: successful
    post:
      summary: create listing
      responses:
        '200':
          description: successful
  "/api/categories/{category_id}/listings/{id}":
    parameters:
    - name: category_id
      in: path
      description: category_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show listing
      responses:
        '200':
          description: successful
    patch:
      summary: update listing
      responses:
        '200':
          description: successful
    put:
      summary: update listing
      responses:
        '200':
          description: successful
    delete:
      summary: delete listing
      responses:
        '200':
          description: successful
  "/api/profiles/{id}/toggle":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    post:
      summary: toggle profile
      tags:
      - Profiles
      responses:
        '200':
          description: successful
  "/api/profiles":
    get:
      summary: list profiles
      tags:
      - Profiles
      responses:
        '200':
          description: successful
    post:
      summary: create profile
      tags:
      - Profiles
      responses:
        '200':
          description: successful
  "/api/profiles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show profile
      tags:
      - Profiles
      responses:
        '200':
          description: successful
    patch:
      summary: update profile
      tags:
      - Profiles
      responses:
        '200':
          description: successful
    put:
      summary: update profile
      tags:
      - Profiles
      responses:
        '200':
          description: successful
    delete:
      summary: delete profile
      tags:
      - Profiles
      responses:
        '200':
          description: successful
  "/api/users/sign_in":
    post:
      summary: create authentication
      tags:
      - Users
      responses:
        '200':
          description: successful
  "/api/users/sign_out":
    delete:
      summary: delete authentication
      tags:
      - Users
      responses:
        '200':
          description: successful
  "/api/users/passwords":
    patch:
      summary: update password
      tags:
      - Users
      responses:
        '200':
          description: successful
  "/api/users/sign_up":
    post:
      summary: create registration
      tags:
      - Users
      responses:
        '200':
          description: successful
  "/api/users/delete":
    delete:
      summary: delete registration
      tags:
      - Users
      responses:
        '200':
          description: successful
  "/api/users/tokens":
    post:
      summary: create token
      tags:
      - Users
      responses:
        '200':
          description: successful
  "/api/me":
    get:
      summary: show user
      tags:
      - Users
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3000
