default: &default
  adapter: postgresql
  encoding: utf-8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USER", 'postgres') %>
  password: <%= ENV.fetch("DB_PASSWORD", 'postgres') %>

development:
  <<: *default
  database: tiksat_development

test:
  <<: *default
  database: tiksat_test

production:
  <<: *default
  database: tiksat_production
  username: tiksat
  password: <%= ENV["TIKSAT_DATABASE_PASSWORD"] %>
