---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $.Values.appType }}-{{ include "apps-backend.branch" . }}-redis"
  namespace: "{{ include "apps-backend.namespace" . }}"
  labels:
    service: "{{ $.Values.appType }}-{{ include "apps-backend.branch" . }}-redis"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      service: "{{ $.Values.appType }}-{{ include "apps-backend.branch" . }}-redis"
  template:
    metadata:
      labels:
        service: "{{ $.Values.appType }}-{{ include "apps-backend.branch" . }}-redis"
    spec:
      containers:
        - name: service
          image: "redis:7-alpine"
          livenessProbe:
            exec:
              command:
                - "/bin/true"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 30
          readinessProbe:
            exec:
              command:
                - "/bin/true"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 30
          ports:
            - name: "redis"
              containerPort: 6379
          resources:
            requests:
              memory: "16Mi"
              cpu: "50m"
              ephemeral-storage: "256Mi"
            limits:
              memory: "128Mi"
              cpu: "250m"
              ephemeral-storage: "256Mi"

---
apiVersion: 'v1'
kind: 'Service'
metadata:
  name: "{{ $.Values.appType }}-{{ include "apps-backend.branch" . }}-redis"
  namespace: "{{ include "apps-backend.namespace" . }}"
spec:
  type: ClusterIP
  selector:
    service: "{{ $.Values.appType }}-{{ include "apps-backend.branch" . }}-redis"
  ports:
    - port: 6379
      targetPort: 6379
