---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.appType }}-default-env-{{ include "apps-backend.branch" . }}-sidekiq
  namespace: "{{ include "apps-backend.namespace" . }}"
data:
  REDIS_URL: "redis://{{ $.Values.appType }}-{{ include "apps-backend.branch" . }}-redis.{{ include "apps-backend.namespace" . }}.svc.cluster.local:6379/0"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $.Values.appType }}-{{ include "apps-backend.branch" . }}-sidekiq"
  namespace: "{{ include "apps-backend.namespace" . }}"
  labels:
    service: "{{ $.Values.appType }}-{{ include "apps-backend.branch" . }}-sidekiq"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      service: "{{ $.Values.appType }}-{{ include "apps-backend.branch" . }}-sidekiq"
  template:
    metadata:
      labels:
        service: "{{ $.Values.appType }}-{{ include "apps-backend.branch" . }}-sidekiq"
    spec:
      containers:
        - name: service
          image: "{{ $.Values.image }}"
          command:
            - /bin/sh
            - -c
            - 'bundle exec sidekiq -C config/sidekiq.yml'
          livenessProbe:
            exec:
              command:
                - "/bin/true"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 30
          readinessProbe:
            exec:
              command:
                - "/bin/true"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 30
          ports:
            - name: "http"
              containerPort: 3000
          env:
            - name: RUN_ENV
              value: "{{ $.Values.branch }}"
            - name: DB_NAME
              value: "backend-{{ $.Values.branch }}"
          envFrom:
            - configMapRef:
                name: {{ $.Values.appType }}-default-env-{{ include "apps-backend.branch" . }}
                optional: false
            - secretRef:
                name: {{ $.Values.appType }}-env
                optional: false
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
              ephemeral-storage: "256Mi"
            limits:
              memory: "768Mi"
              cpu: "1000m"
              ephemeral-storage: "256Mi"
