---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: "{{ $.Values.appType }}-{{ include "apps-backend.branch" . }}-retry"
spec:
  retry:
    attempts: 10
    initialInterval: 100ms

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ $.Values.appType }}-{{ include "apps-backend.branch" . }}"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ $.Values.branch }}.{{ $.Values.domain }}`)
      middlewares:
        - name: "{{ $.Values.appType }}-{{ include "apps-backend.branch" . }}-retry"
      kind: Rule
      services:
        - name: "{{ $.Values.appType }}-{{ include "apps-backend.branch" . }}"
          port: 80
  tls:
    certResolver: main-le
